name: Searxng
services:
    searxng:
        container_name: searxng
        ports:
            - 8888:8080
        volumes:
            - ./config/:/etc/searxng/
            - ./data/:/var/cache/searxng/
        image: docker.io/searxng/searxng:latest
